### ISSUE TITLE
Utilize built-in BMLoop data structure

### ISSUE THREAD

**Issue by awsr** [BenjaminSauder/EdgeFlow#1]
Instead of manually getting the edge loop by repurposing the selection code, wouldn't it be simpler to use the [built-in BMLoop object](https://docs.blender.org/api/blender_python_api_current/bmesh.types.html#bmesh.types.BMLoop)?

```python
e = bm.edges[0] # edge at the start of the edge loop

# get BMLoop that points to the right direction
for loop in e.link_loops:
    if len(loop.vert.link_edges) == 4:
        break

# stop when reach the end of the edge loop
while len(loop.vert.link_edges) == 4:

    # jump between BMLoops to the next BMLoop we need
    loop = loop.link_loop_prev.link_loop_radial_prev.link_loop_prev

    # following edge in the edge loop
    e_next = loop.edge
```
Source: [Mikhail Rachinskiy on Stack Exchange](https://blender.stackexchange.com/a/79995)

He does say:
> This example code works **only** with manifold geometry where all face normals facing one direction. 

I'm not sure whether his comment means that it only works with manifold geometry or if that's simply a requirement when working with manifold geometry.

**Comment by BenjaminSauder** [comment]
hey!

thats what i actually do - but the way blender selects loops is a bit more advanced. for example this code does not handle open borders, nor does it handle ngons. For example double click an edge of a cylinder cap should select the whole cap.  So I had to dig into this stuff, which is interessting, but also a bit of a waste of time, as its already implemented in the C code of blender..

personally I donbt care about non manifold meshes :)
