### ISSUE TITLE
Running operators when no objects are selected

### ISSUE THREAD

**Issue by MarshmallowCirno** [BenjaminSauder/EdgeFlow#10]
Both "set flow" and "set linear" operators won't work if there were no selected object prior to entering edit mode. To reproduce it 

1. select editable mesh object in object mode
2. deselect all objects
3. press tab to enter edit mode
4. run "set linear" operator on edges

blender will throw error, because of this line
`self.objects = set(context.selected_editable_objects)`
in this scenario context.selected_editable_objects list is empty, so self.objects would be empty too
I fixed it by changing 40 line in op_set_edge_flow.py to
`self.objects = set(context.selected_editable_objects) if context.selected_editable_objects else set([context.object])`

**Comment by BenjaminSauder** [comment]
oh nice - very good catch! 

Will check this in the next days :)

**Comment by Neltulz** [comment]
I have been meaning to report this for a while, as I was wondering why this was happening sometimes with my Edge Curve+ add-on which relies upon Edge Flow.

I got around it by forcing the active object to become selected if no objects are selected before running the edge flow operator.  Of course, that only resolves it for my add-on, it's much better to have it resolved in the Edge Flow add-on. :)

@MindlessCirno - Thanks for reporting this! :)

Thanks!

**Comment by Asortofcode** [comment]
Set Linear does this to my model. Why that? Set Flow works fine, though. Blender 2.82.7.
![opvTTQPfVO](https://user-images.githubusercontent.com/56174257/81411877-471ada80-9143-11ea-89fd-da7ea3954d63.png)

**Comment by BenjaminSauder** [comment]
you are using it wrongly.

set linear make a loop straight from the start point to the end point. in
your case it the loops seems to circular, so it does some random crap.

Am Fr., 8. Mai 2020 um 15:50 Uhr schrieb Asortofcode <
notifications@github.com>:
