### ISSUE TITLE
Unexpected result

### ISSUE THREAD

**Issue by esaytee2** [BenjaminSauder/EdgeFlow#11]
Hi, I have tested the addon and in a specific situation it doesnt work. Please see the picture to see the problem.

It looks like that calculation is not ok when there is an extreme angle.

Cheers
Tomas

![image](https://user-images.githubusercontent.com/20445801/76946022-b0c8f600-6903-11ea-8ea8-fad742d02eda.png)

**Comment by BenjaminSauder** [comment]
this is to be expected with the way the algorithm works - see main page for this.
