### ISSUE TITLE
set linear bug on blender 2.82a

### ISSUE THREAD

**Issue by Lu-Do** [BenjaminSauder/EdgeFlow#12]
hi. first of all i love this tool, thanks a lot for sharing this (better  than the maya versione imho)
it worked just fine on 2.8, but there is an issue on the set linear tool in 2.82a that crunch all vertices 
thanks again
![vlc_2020-03-28_16-12-12](https://user-images.githubusercontent.com/9169182/77826311-eb563e00-710e-11ea-93b6-f8e6672d5f7c.png)
![vlc_2020-03-28_16-12-25](https://user-images.githubusercontent.com/9169182/77826313-ed200180-710e-11ea-9959-c878f02a5601.png)

**Comment by BenjaminSauder** [comment]
is the selection a full circle loop going around?

**Comment by Lu-Do** [comment]
hi Benjamin!
yes, for example, i create a sphere, go to edit mode, ctrl+alt select an edgeloop, then Rightclick->SetLinear.

**Comment by Lu-Do** [comment]
so sorry man i just realize i just didn't understand the proper way to use it i guess.
i have to select what in maya is called a "ring" instead of a "loop", so no continous flow of edge has to be selected, but a series in a raw. sorry to have bothered you! this tool is awesome
