### ISSUE TITLE
Blender 2.9

### ISSUE THREAD

**Issue by seanr** [BenjaminSauder/EdgeFlow#13]
Will this need anything more than a `bl_info` update for 2.9? Happy to help test. :)

**Comment by seanr** [comment]
That initial step done here: https://github.com/BenjaminSauder/EdgeFlow/compare/master...seanr:blender_29?expand=1

I'll test this over the next few days as time permits and make any necessary changes I can find.

**Comment by seanr** [comment]
TBH, I don't know if that change is actually needed, but I can confirm that with it it works in the current version. If it does work without that change, by all means just close this. :wink:

**Comment by variaMech** [comment]
UPDATE: I found out what was wrong. The plugin is working. I needed to go into Object mode > apply > scale to reset its transforms before the addon worked properly. I'm not sure if it's a bug or it's intended so I'm going to leave this post up.


Hello, I've just installed this plugin on Blender 2.90.1 and I'm having trouble making it work. Hopefully, this is the correct place to report it. (I'm new to blender and GitHub so apologies in advance.)

Set Flow command does nothing.

Set Linear gives me the following error:

Traceback (most recent call last):
  File "C:\Users\Marcos\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\EdgeFlow\op_set_edge_linear.py", line 40, in invoke
    distance /= edge_count
ZeroDivisionError: division by zero

location: <unknown location>:-1

Thank you!

**Comment by ngowangvinh** [comment]
Please update this tool to Blender 2.91!

**Comment by Dez1gner** [comment]
Pls update to 2.9

**Comment by BenjaminSauder** [comment]
It should work just fine in 2.93 no updates needed.

**Comment by JFawcett85** [comment]
in 3.0 Blender, edge flow is having an issue. When I select the edge I want edgeflow to mimic, it takes the edge I had selected and moves the edge about a third the distance into the meshes center as well scales it down. I am doing this on a perfect cylinder. I created a new cube and select an edge and applied edgeflow, and still does the same thing.
