### ISSUE TITLE
Blender 3.0 issues(NEVERMIND)

### ISSUE THREAD

**Issue by JFawcett85** [BenjaminSauder/EdgeFlow#15]
NEVERMIND! FIGURED IT OUT

in 3.0 Blender, edge flow is having an issue. When I select the edge I want edgeflow to mimic, it takes the edge I had selected and moves the edge about a third the distance into the meshes center as well scales it down. I am doing this on a perfect cylinder. I created a new cube and select an edge and applied edgeflow, and still does the same thing.

**Comment by BenjaminSauder** [comment]
So you figured out?
