### ISSUE TITLE
Set flow and set linear don't work with repeat last (Shift+R)

### ISSUE THREAD

**Issue by rurre** [BenjaminSauder/EdgeFlow#16]
Using set flow or set linear then selecting something else and hitting Shift+R to repeat last action doesn't seem to work.
Instead it just selectes whatever set flow or set linear was used on last.

**Comment by BenjaminSauder** [comment]
Yeah I'm aware of this - been tinkering on an update last few days, maybe I can look into this as well.

**Comment by BenjaminSauder** [comment]
@rurre hey this is adressed in the dev branch
