### ISSUE TITLE
Sometime it stops working.

### ISSUE THREAD

**Issue by Aurontwist** [BenjaminSauder/EdgeFlow#17]
Something down the line brakes the tool.

To make it work again:

1. Deselect edges
2. I have to leave edit mode 
2. select an other object. 
3. jump in edit mode.
4. select something
5. leve edit mode
6. Select the first object
7. go in edit mode
8. select again the edges
9. NOW IT WORKS

I wonder if anybody facing the same issue. 

Hope my issue submission makes the tool even more ososm.

All the best.

**Comment by tempdevnova04** [comment]
Yep have the same issues, seems to be too sporadic to reproduce though

**Comment by arsenio22** [comment]
I have the same/similar issue as well. 

Summary of issue:
-Randomly stops working
-Exacerbated by applying transform all. 
-After applying transform all, "set linear" encounters the "division by zero" error. 

Random temporary fix:
-Jumping to another program like safari and back to blender.
-Adding a random object in object mode then back to the main object
-When set linear encounters "division by zero" error. It's almost as sure  indicator that the set flow will not work.

System being used:
-Mac m1 16gb ram
-Blender 3.3

Nonetheless, Thank you for making this add-on :)

**Comment by BenjaminSauder** [comment]
I need a better repro case for this. this is too much fishing in the dark ;)
