### ISSUE TITLE
New feature: Blend from start and/or end point

### ISSUE THREAD

**Issue by IngoClemens** [BenjaminSauder/EdgeFlow#19]
I have added a new feature to blend from either the start or end point (or both) which is very convenient when working with edge loops which span across a surface with different features. Currently the adjusted edge loop will be placed at the center between it's surrounding loops. But sometimes the start or end point of the loop needs to stay put to preserve the surface feature in this area. And adjusting loop positions can be quite tedious when done manually.

I already tried to contact you via Twitter because posting this new feature seems to draw much attention.

For now I forked your project to provide a custom version to the public because this new feature is extremely helpful.
I just didn't want to skip over your head and let you know. The project has been quiet for some time and I don't know if you plan to develop this tool further. It's a real time saver. Thank you very much for it.

**Comment by BenjaminSauder** [comment]
hey, yes ive seen the thread.

feel free to do a PR on the Dev branch:
https://github.com/BenjaminSauder/EdgeFlow/tree/dev

I sometimes do some stuff there, would be a nice addition for a 'proper' 4.0 update..

For single edge loops this surely works quite nicely, but how does it behave with multiple loops? Because I fear that the start - end points are pretty random. This is obviously not the end of the world... just something to think about.

**Comment by IngoClemens** [comment]
Hey, thanks for the quick reply.
It already works with a multiple selection. I basically added my own edge sorting algorithm because it was too time consuming to detangle your code. Probably not the most efficient but it works.

Yes, start and end points can be random. But only for the multi-selection. If you have only one loop selected you can guide it by the active edge.

I'm afraid that I have no idea how to do a PR on the dev branch. This whole GitHub stuff is a mystery to me. I only use it for archiving but I am clueless when it comes to branching, merging, pulling, etc.

**Comment by BenjaminSauder** [comment]
just give it a try - its fairly simple on github :) 

the main thing is that its based on the latest dev branch - so i dont have to do any merging ;)

**Comment by IngoClemens** [comment]
I sent you a DM on Twitter with my email. If you want to get in touch I would have some additional info for you.

**Comment by BenjaminSauder** [comment]
I updated the dev branch with this feature.

**Comment by BenjaminSauder** [comment]
its live since a bit.
