### ISSUE TITLE
please rename the menu to something else

### ISSUE THREAD

**Issue by Flowgun** [BenjaminSauder/EdgeFlow#21]
Hello,

love your addon. The only issue I have with it is that it adds "Set Flow" to the context menu, which highlights the first letter (S). This takes away the shortcut from "Subdivide" in Edge mode (making "i" the highlighted letter in "Subdivide").

This is an issue because I like to just right-click and press "S" to subdivide. With EdgeFlow addon installed, subdividing is done with "S" in face mode, but with "i" in edge mode, breaking consistency.

I always rename "Set Flow" to just "Flow" after installing the addon to keep my "S" key for subdividing, but it would be nice to just have that working consistently just after installing/updating the addon.

**Comment by mikedizhur** [comment]
Easy fix: you can change line 61 in \_\_init\_\_.py to  `bl_label = "Edge Flow"`  or whatever name you want.

**Comment by BenjaminSauder** [comment]
yeah sorry this seems like a thing you have to take care of yourself as [mikedizhur](https://github.com/mikedizhur) commented.
the order in that menu is rather arbitrary anyway.. for example the ctrl-e menu has the screw operator for hotkey s.
