### ISSUE TITLE
Mix "wobbles"

### ISSUE THREAD

**Issue by ettiSurreal** [BenjaminSauder/EdgeFlow#23]
I think this is easier to just show than explain.

https://github.com/BenjaminSauder/EdgeFlow/assets/98223724/5f256f08-40c9-423c-9a30-b9c2ed7aae7f

Affects both Set Flow and Set Curve.
Also small suggestion while we're here, since mix already exists for these two tools, it would be nice to have it on the rest.

**Comment by BenjaminSauder** [comment]
yes, this behaviour is a bit strange.

tried to fix it this afternoon 18ccdf09372ba1ef11a34f0f55506f3dd0cc251d - also worked a bit on harmonizing the mix feature across all operators...

so you can try the latest master version? Not sure if I broke something, was a bit icky to  handle this.

**Comment by ettiSurreal** [comment]
Works now!
