### ISSUE TITLE
Right-click context keyboard shortcut

### ISSUE THREAD

**Issue by acadgatsu** [BenjaminSauder/EdgeFlow#25]
Hi, 

I use the right-click context menu's shortcut S for subdivide all the time in vert, edge, and face mode. With the edgeflow add-on enabled,  the S shortcut key while in context menu is now taken and subdivide is now different keys for vert, edge, face. Is this something that is being specified in the edge flow addon or an automated assignment from a blender setting that I may change? I'm seeing this change in 4.1 with version 0.8 - in blender 3.6.2 with version 0.5 I have no problem. thank you.

**Comment by schroef** [comment]
There is a closed issue which shows how to change the name to "edge flow". This will solve the issue.

See issue #21

**Comment by BenjaminSauder** [comment]
the right click menu is not more configurable:

https://github.com/BenjaminSauder/EdgeFlow/commit/87e275c49426c24f2fb723cd5c403351ca420c6b
