### ISSUE TITLE
Any plans to add Edgeflow to the new Extension Platform?

### ISSUE THREAD

**Issue by Dangry98** [BenjaminSauder/EdgeFlow#26]
Would be nice to have the add-on available on the new extension platform, any plans?
Please submit to https://extensions.blender.org/

**Comment by BenjaminSauder** [comment]
Hey, even before you wrote this some work on making this possible has started.

Will take a bit of time tho.

**Comment by Dangry98** [comment]
> Hey, even before you wrote this some work on making this possible has started.
> 
> Will take a bit of time tho.

Awsome! Thanks for the amazing work you are doing!
