### ISSUE TITLE
[enhancement] Preferences to disable right click additions

### ISSUE THREAD

**Issue by LalaGhost** [BenjaminSauder/EdgeFlow#27]
I installed the add on and since it now appears in my right click menu it messes with my shortcuts that I have muscle memory for. 
When the right click menu it edit mode is open now "S" is for "Set Flow" and not "Subdivide" and because of that all following functions after Subdivide get assigned a different key.

Would it be possible to add a checkbox to the preferences to disable the additions to the right click menu?

**Comment by BenjaminSauder** [comment]
This should be adressed now, I added preferences to the addon, can toggle on/off the right click menus - and pick where you want the entries added.

https://github.com/BenjaminSauder/EdgeFlow/commit/87e275c49426c24f2fb723cd5c403351ca420c6b
