### ISSUE TITLE
Plans to add to Extension Platform?

### ISSUE THREAD

**Issue by Dangry98** [BenjaminSauder/EdgeFlow#29]
Hi, any plans to add to the Blender Extension platform?
https://extensions.blender.org/

**Comment by BenjaminSauder** [comment]
Hey, this will happen soonish - basically as when ill be switching over to 4.2 blender myself. Lets see..

**Comment by Dangry98** [comment]
Hi, any updates? This is kinda one of the last "must have" add-ons thats not on the Extension Platform yet. Having acces to the new update functionlity and easy of install it provides would be super handy!

**Comment by BenjaminSauder** [comment]
@Dangry98 it will happen - ive been slacking on this. Ill try to find some time for this.

**Comment by Dangry98** [comment]
> @Dangry98 it will happen - ive been slacking on this. Ill try to find some time for this.

Awesome! Thank you, looking forward to it!

**Comment by BenjaminSauder** [comment]
https://extensions.blender.org/add-ons/edgeflow/

**Comment by Dangry98** [comment]
> https://extensions.blender.org/add-ons/edgeflow/

Thank you so much! :) Awesome to see!
