### ISSUE TITLE
Custom Flow Profiles?

### ISSUE THREAD

**Issue by JR3DFUL** [BenjaminSauder/EdgeFlow#30]
Seeing as you already support Curve and Linear, do you think it'd be possible to allow custom curve profiles for more control?

![image](https://github.com/user-attachments/assets/10295604-7024-4e29-894a-d6d6edfe95e6)

**Comment by BenjaminSauder** [comment]
To my knowlege this widget is not exposed to the python api - and I'm also not sure how this would actually be all that usefull.
