### ISSUE TITLE
Live UV Unwrap/Update

### ISSUE THREAD

**Issue by elstinopacino** [BenjaminSauder/EdgeFlow#31]
Could you make this work with the live UV Unwrap fuction? I don't know what happens here under the hood so it might be quite a thing I'm asking but either way I thought I'd try :)

**Comment by BenjaminSauder** [comment]
hmm good question - guess i could have a look.. :D

**Comment by BenjaminSauder** [comment]
ok - checked this, and as no other modelling tool triggers an unwrap update when live unwrap is enabled ill leave that as is, as its more in line how tools behave in blender itself.

**Comment by elstinopacino** [comment]
Oh yeah, thanks for looking into it and all the best!
