### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by teck968** [BenjaminSauder/EdgeFlow#5]
Following the installation directions in the readme does not appear to work. The add-on reports no errors, however it does not show up in the add-ons list, and therefore can not be enabled. I am using Blender 2.8, the latest official release as of 08/08/2019. Please advise.

**Comment by BenjaminSauder** [comment]
I think I messed up the zip there.

Can you try this:

* Get the latest EdgeFlow.zip release in: https://github.com/BenjaminSauder/EdgeFlow/releases
* start Blender and open the user preferences
*  switch to the Add-ons tab and click the Install Add-on from file... button at the bottom
* locate the downloaded EdgeFlow.zip file and double-click it
* search for the addon "EdgeFlow"
* activate the addon by ticking the checkbox (hit the Save User Settings button at the bottom if your blender is setup that way)

**Comment by teck968** [comment]
This appears to work.

Thanks,
  Jeremy
