### ISSUE TITLE
Feature Request: Get rid of Iteration Max limit

### ISSUE THREAD

**Issue by Neltulz** [BenjaminSauder/EdgeFlow#8]
If you open up the `op_set_edge_flow.py` file, and go to line 84, you'll see:
`iterations : IntProperty(name="Iterations", default=1, min=1, max=32)`

Can you change max to be soft_max like this:
`iterations : IntProperty(name="Iterations", default=1, min=1, soft_max=32)`

This will get rid of the hard maximum on the number of iterations.  It will allow users to type a number higher than 32, but the slider will still be confined to 32.

The reason I would like this to be changed is because in my addon, I can insert multiple loop cuts, and then apply edge flow to the newly added loops, and the hard limit of 32 iterations prevents the edges from being smoothed correctly.  I really need at least 128 iterations.

Before: https://i.imgur.com/CpvTbAQ.jpg
After with 32 iterations: https://i.imgur.com/B4B5vEr.jpg <-- Bad result
After with 128 iterations: https://i.imgur.com/BEOBu9c.jpg <-- Good result

As you can see, when inserting 8 edge loops with 128 iterations, it turns out much better! :)

Edit: I just found a case where I needed 512 iterations to create a perfect result.

Before: https://i.imgur.com/g6HBjwP.png
After with 512 iterations: https://i.imgur.com/g6HBjwP.png

Hopefully you consider!
-Neil

**Comment by BenjaminSauder** [comment]
i changed it.
