### ISSUE TITLE
Feature Req: Linear Interpolate Vertex Positions Between 0-1

### ISSUE THREAD

**Issue by Neltulz** [BenjaminSauder/EdgeFlow#9]
Hi, just a simple feature request.  Sometimes even just 1 iteration can produce a very drastic result depending on the usage scenario.

The ability to drag a slider from 0-1 (or 0% to 100%) to interpolate the original vertex positions with the final positions would be very useful! :)

If implemented, I recommend 100% as the default value, so that the addon does not cause any compatibility issues with my Edge Curve Plus addon.

Thanks for your consideration! :)

**Comment by BenjaminSauder** [comment]
I'm tinkering with updating the add-on - maybe I find time to try this idea.

**Comment by BenjaminSauder** [comment]
should be there in the dev branch - i decided to call it 'mix'
